export const QUERY_GENRES_LIST = 'genres_list'
export const QUERY_MOVIES_LIST = 'movies_list'
export const QUERY_TOP_MOVIES_BY_GENRE = 'top_movies_by_genre'
export const QUERY_MOVIES_DETAILS = 'movie_details'
export const QUERY_RELATED_MOVIES = 'related_movies'
